name: CI

on: [push, pull_request]

jobs:
  tests-5-to-9:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [5.x, 6.x, 7.x, 8.x, 9.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test
      run: |
        npm install
        npm test
      env:
        CI: true

  tests-10-to-13:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test
      run: |
        npm ci
        npm test
      env:
        CI: true
